### ISSUE TITLE
High memory usage from ResourceHelper

### ISSUE THREAD

**Issue by Ricket** [AgriCraft/AgriCore#10]
![image](https://user-images.githubusercontent.com/196978/115346875-5b01f580-a176-11eb-95d0-bcb9c78d6e16.png)

I was looking at a heap dump and noticed 131mb of memory usage from `com.agricraft.agricore.util.ResourceHelper`. The hashmap is large and seems to refer to all of the resources available in the classpath. I wonder if this is necessary or could it be improved to save some memory?

I'm on mod version `AgriCraft-2.12.0-1.12.0-a6`. (MC Eternal modpack version 1.4.3.1)

**Comment by InfinityRaider** [comment]
Thanks for reporting this good find!

The cause seems to be an internal map in org.reflections.Reflections, which we are using to find json files (plants, soils, mutations) on the classpath.
I was, however, not aware that keeping an instance of Reflections around was this memory intensive.
It can definitely be improved by discarding the Reflections instance once we do not use it anymore.
